Fixed multiple number support and validate after authentication
wso2-extensions/identity-outbound-auth-duo pull request #15
Opened 2017-06-29 12:45 UTC by Kanapriya

2017-06-30 05:57 UTC, malakasilva requested changes

2017-06-30 05:57 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java
> +        String loginPage = ConfigurationFacade.getInstance().getAuthenticationEndpointURL();
Please verify with IS team if this is the best way to do this.

2017-06-30 05:57 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java
> +        String loginPage = ConfigurationFacade.getInstance().getAuthenticationEndpointURL();
If we deploy this webapp seperately this won't work I guess?

2017-06-30 05:57 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java
> +            throw new InvalidCredentialsException("Error while getting the mobile number from user's profile " +
Is this the proper exception in this case?

2017-06-30 05:57 UTC, malakasilva commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java
> +                if (((JSONObject) phoneArray.get(i)).getString(DuoAuthenticatorConstants.DUO_NUMBER).equals(mobile)) {
This can throw nullpointexception.

2017-07-03 08:04 UTC, Kanapriya commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java
> +            throw new InvalidCredentialsException("Error while getting the mobile number from user's profile " +
Fixed in dac301bab07386ebd20752700a6e4862afd985b1

2017-07-03 08:04 UTC, Kanapriya commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java
> +        String loginPage = ConfigurationFacade.getInstance().getAuthenticationEndpointURL();
Fixed in dac301bab07386ebd20752700a6e4862afd985b1

2017-07-03 08:06 UTC, Kanapriya commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/duo/DuoAuthenticator.java
> +                if (((JSONObject) phoneArray.get(i)).getString(DuoAuthenticatorConstants.DUO_NUMBER).equals(mobile)) {
Before calling this method , we have whether the mobile number is empty or not 
https://github.com/wso2-extensions/identity-outbound-auth-duo/pull/15/files#diff-318fa0251bfd40a605a65f7b90ee41c5R176

2017-07-03 08:08 UTC, malakasilva approved these changes

2017-07-03 08:10 UTC, merged